### PR TITLE
Implement header component for Reaction Swag Shop

### PR DESCRIPTION
**Pull request by prinzdezibel**
This PR addresses #1 : Creating a header for all pages.

### CODE REVIEW

**Comment by prinzdezibel** [comment]
@zenweasel  I've had some problems with getTopVariant. The product pictures were not imported, once I've called it. Maybe I'm doing something wrong, I'd have to look into it again. Perhaps you spot the error at first glance. For now, I've commented it out though.

**Comment by prinzdezibel** [comment]
@zenweasel: On a side-note regarding CSS - just in case you wonder about it when reviewing the PR:   I've had good experience in another project with  [Block-Element-Modifier](http://getbem.com/introduction/) convention for naming CSS classes. Its whole purpose is to avoid different CSS specificity values, because that does more harm than doing good, IMHO.


For example, when using traditional CSS with a lot of nesting, it's really difficult to reuse/override styles from stock reaction. One example: I had quite difficulties to set the margin of our `.brand` component. The browser just didn't catch my override because the overall specificity was too low until I copied the whole cascade from default-theme:

```
html:not(.rtl) .rui.navbar .brand {
 margin-left: 30px;
}
```
(Btw, I'm now realizing that I probably should've left out the pseudo class `:not(.rtl)`, but still my argument holds true.)

And secondly it would make refactoring  a lot less pain, when juggling with the structure of the HTML itself, like swapping child and parent elements.


Thinking about it, I'm not sure if I should go the BEM route, because the core has it's own convention anyway, which I need to respect in order to be able to override styles. Maybe I should just stick with that too, because it may confuse people.

@mikemurray A bit off-topic: What's Reaction's take on alternative CSS technologies, like CSS-in-Javascript? Or other methodologies like the Block-Element-Modifier convention mentioned above? The current way of doing is tad too brittle in my opinion.

**Comment by mikemurray** [comment]
@prinzdezibel 

CSS-in-JS Generally don't use. It's currently used for a few admin things that require CSS-in-JS for some animation and layout things in real time based on the size of the window. Otherwise, for most components, especially ones to be modified by others, don't use CSS-in-JS.

---

BEM don't use since it looks weird alongside the bootstrap CSS. At one point I did try to use BEM, but I've since reverted that.

You are welcome to make more tailored class names if you want to avoid a specifcity war, like doing:
`className="rui navbar-brand"` instead of relying on hierarchy. That way you can target a specific element instead of doing something like `html:not(.rtl) .rui.navbar .brand` you could then do `html:not(.rtl) .rui.navbar-brand`.

**Comment by prinzdezibel** [comment]
@mikemurray I get your point and I was already thinking of ditching BEM again.

But still the specificity nightmare is not gone as long as base CSS does make usage of heavily nested selectors. Just saying: e.g. considering your example I think it's not possible to override a rule without copying the whole cascade into the users plugin (Even with tailored class names, which also would require users to go the extra mile and alter the rendered markup).
 
Assuming `html:not(.rtl) .rui.navbar .brand` is a used rule in our stock theming I'd like to overwrite, I don't see how `html:not(.rtl) .rui.navbar-brand` can help me (specificity is lower, also targets not the brand element, but the navbar-brand parent). Maybe I'm missing something obvious?

**Comment by zenweasel** [comment]
@prinzdezibel I tried to test this but it doesn't appear that instructions for copying files are correct/complete and it also looks like you have a conflict.

**Comment by prinzdezibel** [comment]
This PR is superseded by #21. It uses obsolete path declarations to load assets. Going to close.

**Pull request closed without merging**
